/**
 * SectMerge — drag-and-drop promotion grid for the Roster.
 *
 * Economy (Option D): Place costs Merit (passively generated by owned
 * disciples), Expand costs Qi. Merit accrues lazily — the component runs
 * a local 1Hz display tick so the player sees the balance climb in real
 * time without forcing App.jsx to re-render.
 *
 * Pointer events handle both touch + mouse for drag-merge:
 *   pointerdown → record fromIdx
 *   pointermove (window) → update ghost, find drop target via
 *                          document.elementFromPoint
 *   pointerup (window)   → call merge.drop(fromIdx, toIdx)
 *
 * Grid size is dynamic (3..7) via inline CSS custom property.
 */
import { useState, useEffect, useRef, useCallback } from 'react';
import useDiscipleMerge, { currentMerit } from '../../hooks/useDiscipleMerge';
import { TIERS, BONUS_PER_BOARD_SUM, gridIsFull } from '../../data/discipleMerge';
import { fmt } from '../../utils/format';

const BASE = import.meta.env.BASE_URL;
const spriteUrl = (s) =>
  (typeof s === 'string' && s.startsWith('/')) ? `${BASE}${s.replace(/^\//, '')}` : s;

function Tile({ tile }) {
  const t = TIERS[tile.tier];
  return (
    <div className="dmg-tile">
      <img
        className="dmg-tile-sprite"
        src={spriteUrl(t.sprite)}
        alt={t.rank}
        draggable={false}
      />
      {t.badge && <span className="dmg-tile-badge">{t.badge}</span>}
      <span className="dmg-tile-tier">T{tile.tier}</span>
    </div>
  );
}

export default function SectMerge({ owned = 0, qi = 0, spendQi }) {
  const merge = useDiscipleMerge();
  const [drag, setDrag] = useState(null);          // { fromIdx, x, y, pointerId } | null
  const [overIdx, setOverIdx] = useState(null);
  const [selectedIdx, setSelectedIdx] = useState(null);
  const [animFlags, setAnimFlags] = useState({});  // { [idx]: 'merge' | 'spawn' }
  const [, setDisplayTick] = useState(0);          // forces re-render at 1Hz for Merit clock
  const animTimers = useRef([]);

  // Local display tick — drives the Merit "live" number without polluting
  // App.jsx with a setInterval that triggers global re-renders. Stops when
  // the player closes the minigame (component unmount cleans up).
  useEffect(() => {
    const id = setInterval(() => setDisplayTick(t => t + 1), 500);
    return () => clearInterval(id);
  }, []);

  // Cleanup any pending anim timers on unmount.
  useEffect(() => () => { animTimers.current.forEach(clearTimeout); }, []);

  if (!merge) return null;

  const { state, place, drop, seclude, expand, sum, perDiscipleBonusPct,
          nextPlaceCost, nextExpansion, highestTier, gridSize, MERIT_RATE } = merge;
  const tiles = state.tiles;
  const full = gridIsFull(tiles);

  // Live Merit (lazy compute)
  const meritNow = currentMerit(state, owned);
  const meritPerSec = owned * MERIT_RATE;

  const flagAnim = (idx, kind, ms = 700) => {
    setAnimFlags(prev => ({ ...prev, [idx]: kind }));
    const t = setTimeout(() => {
      setAnimFlags(prev => {
        const next = { ...prev };
        delete next[idx];
        return next;
      });
    }, ms);
    animTimers.current.push(t);
  };

  // ── Pointer drag ──────────────────────────────────────────────────────────
  const handlePointerDown = useCallback((idx) => (e) => {
    if (!tiles[idx]) return;
    if (e.button !== undefined && e.button !== 0) return;
    setDrag({ fromIdx: idx, x: e.clientX, y: e.clientY, pointerId: e.pointerId });
    setSelectedIdx(idx);
    setOverIdx(null);
  }, [tiles]);

  useEffect(() => {
    if (!drag) return;
    const onMove = (e) => {
      if (e.pointerId !== drag.pointerId) return;
      e.preventDefault();
      const nx = e.clientX, ny = e.clientY;
      setDrag(d => d ? { ...d, x: nx, y: ny } : d);
      const el = document.elementFromPoint(nx, ny);
      const cell = el?.closest('.dmg-cell');
      if (cell && cell.dataset.idx !== undefined) {
        const i = Number(cell.dataset.idx);
        setOverIdx(i === drag.fromIdx ? null : i);
      } else {
        setOverIdx(null);
      }
    };
    const onUp = (e) => {
      if (e.pointerId !== drag.pointerId) return;
      const fromIdx = drag.fromIdx;
      let toIdx = overIdx;
      if (toIdx === null) {
        const el = document.elementFromPoint(e.clientX, e.clientY);
        const cell = el?.closest('.dmg-cell');
        if (cell && cell.dataset.idx !== undefined) {
          const i = Number(cell.dataset.idx);
          if (i !== fromIdx) toIdx = i;
        }
      }
      setDrag(null);
      setOverIdx(null);
      if (toIdx === null) return;
      const result = drop(fromIdx, toIdx);
      if (result?.action === 'merge') {
        flagAnim(toIdx, 'merge', 720);
        setSelectedIdx(null);
      } else if (result?.action === 'move' || result?.action === 'swap') {
        setSelectedIdx(null);
      }
    };
    window.addEventListener('pointermove', onMove, { passive: false });
    window.addEventListener('pointerup', onUp);
    window.addEventListener('pointercancel', onUp);
    return () => {
      window.removeEventListener('pointermove', onMove);
      window.removeEventListener('pointerup', onUp);
      window.removeEventListener('pointercancel', onUp);
    };
  }, [drag, overIdx, drop]);

  // ── Tap (no-drag click) ───────────────────────────────────────────────────
  const handleCellClick = (idx) => {
    if (drag) return;
    if (!tiles[idx]) {
      // Empty cell shortcut: Place if affordable, else just toggle selection
      if (selectedIdx === null) {
        handlePlace();
      } else {
        setSelectedIdx(null);
      }
      return;
    }
    setSelectedIdx(idx === selectedIdx ? null : idx);
  };

  // ── Place / Expand / Seclude ──────────────────────────────────────────────
  const handlePlace = () => {
    if (full) return;
    if (meritNow < nextPlaceCost) return;
    const out = place(owned);
    if (out?.placed) flagAnim(out.idx, 'spawn', 420);
  };
  const handleSeclude = () => {
    if (selectedIdx === null) return;
    seclude(selectedIdx);
    setSelectedIdx(null);
  };
  const handleExpand = () => {
    if (!nextExpansion) return;
    if (highestTier < nextExpansion.unlockTier) return;
    if (qi < nextExpansion.qiCost) return;
    if (typeof spendQi !== 'function') return;
    expand(spendQi);
  };

  // ── Derived ───────────────────────────────────────────────────────────────
  const draggedTile = drag ? tiles[drag.fromIdx] : null;
  const selectedTile = selectedIdx !== null ? tiles[selectedIdx] : null;

  const canPlace = !full && meritNow >= nextPlaceCost;
  const canExpand = !!nextExpansion && highestTier >= nextExpansion.unlockTier && qi >= nextExpansion.qiCost;
  const tierGateLocked = !!nextExpansion && highestTier < nextExpansion.unlockTier;

  return (
    <div className="dmg">

      {/* Stats banner — Merit lives on the LEFT (the active spend currency),
          Board / Bonus on the right (the payoff readout). */}
      <div className="dmg-stats">
        <div className="dmg-stat">
          <div className="dmg-stat-k">Merit</div>
          <div className="dmg-stat-v dmg-stat-merit">{fmt(Math.floor(meritNow))}</div>
          <div className="dmg-stat-sub">+{meritPerSec.toFixed(1)}/s</div>
        </div>
        <div className="dmg-stat">
          <div className="dmg-stat-k">Board sum</div>
          <div className="dmg-stat-v dmg-stat-violet">{sum}</div>
        </div>
        <div className="dmg-stat">
          <div className="dmg-stat-k">Per disciple</div>
          <div className="dmg-stat-v dmg-stat-gold">×{(1 + perDiscipleBonusPct).toFixed(2)}</div>
          <div className="dmg-stat-sub">+{(perDiscipleBonusPct * 100).toFixed(1)}%</div>
        </div>
      </div>

      {/* Grid — dynamic columns via inline CSS var */}
      <div className="dmg-grid" style={{ '--dmg-cols': gridSize }}>
        {tiles.map((tile, i) => {
          const isSel = selectedIdx === i && !drag;
          const isDragSrc = drag?.fromIdx === i;
          const isOver = overIdx === i;
          let dropKind = '';
          if (isOver && draggedTile) {
            if (!tile) dropKind = 'dmg-drop-move';
            else if (tile.tier === draggedTile.tier && tile.tier < TIERS.length - 1) dropKind = 'dmg-drop-merge';
            else if (tile.tier === draggedTile.tier) dropKind = 'dmg-drop-maxed';
            else dropKind = 'dmg-drop-swap';
          }
          const animClass = animFlags[i] ? `dmg-anim-${animFlags[i]}` : '';
          const cls = [
            'dmg-cell',
            tile ? 'dmg-has-tile' : 'dmg-empty',
            isSel ? 'dmg-selected' : '',
            isDragSrc ? 'dmg-drag-src' : '',
            dropKind,
            animClass,
          ].filter(Boolean).join(' ');
          return (
            <div
              key={tile ? `t-${tile.id}` : `e-${i}`}
              className={cls}
              data-idx={i}
              onPointerDown={tile ? handlePointerDown(i) : undefined}
              onClick={() => handleCellClick(i)}
            >
              {tile ? <Tile tile={tile} /> : <span className="dmg-empty-plus">+</span>}
            </div>
          );
        })}
      </div>

      {/* Drag ghost */}
      {drag && draggedTile && (
        <div className="dmg-ghost" style={{ left: `${drag.x}px`, top: `${drag.y}px` }}>
          <Tile tile={draggedTile} />
        </div>
      )}

      {/* Selection / inspect bar */}
      <div className="dmg-sel">
        {selectedTile ? (
          <>
            <div className="dmg-sel-info">
              <div className="dmg-sel-name">
                <span className="dmg-sel-tier">T{selectedTile.tier}</span>
                {TIERS[selectedTile.tier].rank}
              </div>
              <div className="dmg-sel-sub">
                Value {TIERS[selectedTile.tier].value} · contributes +{(TIERS[selectedTile.tier].value * BONUS_PER_BOARD_SUM * 100).toFixed(2)}% to per-disciple qi/s
              </div>
            </div>
            <button type="button" className="dmg-seclude" onClick={handleSeclude}>
              Seclude
            </button>
          </>
        ) : (
          <div className="dmg-sel-empty">
            Drag two same-rank disciples to promote · drag a different rank to swap
          </div>
        )}
      </div>

      {/* Action row — Place (Merit) + Expand (Qi) */}
      <div className="dmg-actions">
        <button
          type="button"
          className="mg-btn mg-btn-primary dmg-act dmg-act-place"
          onClick={handlePlace}
          disabled={!canPlace}
        >
          {full ? (
            <span className="dmg-act-label">Grid full</span>
          ) : (
            <>
              <span className="dmg-act-label">+ Place Disciple</span>
              <span className="dmg-act-cost">{fmt(nextPlaceCost)} Merit</span>
            </>
          )}
        </button>

        {nextExpansion ? (
          <button
            type="button"
            className="mg-btn mg-btn-ghost dmg-act dmg-act-expand"
            onClick={handleExpand}
            disabled={!canExpand}
            title={tierGateLocked ? `Reach T${nextExpansion.unlockTier} on the board to unlock` : ''}
          >
            {tierGateLocked ? (
              <>
                <span className="dmg-act-label">Expand to {nextExpansion.size}×{nextExpansion.size}</span>
                <span className="dmg-act-cost dmg-act-locked">Need T{nextExpansion.unlockTier}</span>
              </>
            ) : (
              <>
                <span className="dmg-act-label">Expand to {nextExpansion.size}×{nextExpansion.size}</span>
                <span className="dmg-act-cost">{fmt(nextExpansion.qiCost)} Qi</span>
              </>
            )}
          </button>
        ) : (
          <div className="dmg-act dmg-act-maxed">
            <span className="dmg-act-label">Grid maxed</span>
            <span className="dmg-act-cost">{gridSize}×{gridSize}</span>
          </div>
        )}
      </div>

      <div className="dmg-hint">
        Owned disciples generate Merit. Spend it to Place new T1s; merge to promote ranks. Each merge yields Merit equal to the new tile’s value.
      </div>

    </div>
  );
}
