import { useEffect, useRef } from 'react';
import REALMS, {
  stageHasSpark,
  CHAPTERS,
  REALM_NAMES,
  toRoman,
} from '../data/realms';

const BASE = import.meta.env.BASE_URL;

// Pixel-art icons for each major realm, generated by scripts/gen_realm_icons.py.
// Paths are RELATIVE (no leading slash) so vite's BASE_URL — which differs per
// build mode (/, /MartialArtsIdle/ for GH Pages, etc.) — can prefix them at
// runtime. Half-Step Open Heaven has no dedicated icon; falls through to emoji.
const REALM_ICONS = {
  'Tempered Body':          `${BASE}ui/realms/tempered_body.png`,
  'Qi Transformation':      `${BASE}ui/realms/qi_transformation.png`,
  'True Element':           `${BASE}ui/realms/true_element.png`,
  'Separation & Reunion':   `${BASE}ui/realms/separation_reunion.png`,
  'Immortal Ascension':     `${BASE}ui/realms/immortal_ascension.png`,
  'Saint':                  `${BASE}ui/realms/saint.png`,
  'Saint King':             `${BASE}ui/realms/saint_king.png`,
  'Origin Returning':       `${BASE}ui/realms/origin_returning.png`,
  'Origin King':            `${BASE}ui/realms/origin_king.png`,
  'Void King':              `${BASE}ui/realms/void_king.png`,
  'Dao Source':             `${BASE}ui/realms/dao_source.png`,
  'Emperor Realm':          `${BASE}ui/realms/emperor_realm.png`,
  'Open Heaven':            `${BASE}ui/realms/open_heaven.png`,
  'Half-Step Open Heaven':  '🌅',
};

// Chinese single-character glyph for each realm name, used by the journey
// row "icon" tile. Mirrors the calligraphy treatment from the mockup.
const REALM_GLYPHS = {
  'Tempered Body':         '体',
  'Qi Transformation':     '气',
  'True Element':          '元',
  'Separation & Reunion':  '分',
  'Immortal Ascension':    '仙',
  'Saint':                 '圣',
  'Saint King':            '王',
  'Origin Returning':      '归',
  'Origin King':           '源',
  'Void King':             '虚',
  'Dao Source':            '道',
  'Emperor Realm':         '帝',
  'Open Heaven':           '天',
  'Half-Step Open Heaven': '半',
};

function fmtQi(n) {
  if (n >= 1e12) return (n / 1e12).toFixed(1) + 'T';
  if (n >= 1e9)  return (n / 1e9).toFixed(1)  + 'B';
  if (n >= 1e6)  return (n / 1e6).toFixed(1)  + 'M';
  if (n >= 1e3)  return (n / 1e3).toFixed(1)  + 'K';
  return String(n);
}

// Group consecutive realm entries by name. Returned in source order so the
// `realmNameIndex` we attach matches the position in REALM_NAMES.
function groupRealms(realms) {
  const groups = [];
  let current = null;
  let nameIdx = -1;
  realms.forEach((r, idx) => {
    if (!current || current.name !== r.name) {
      nameIdx += 1;
      current = { name: r.name, realmNameIndex: nameIdx, entries: [] };
      groups.push(current);
    }
    current.entries.push({ ...r, index: idx });
  });
  return groups;
}

const GROUPS = groupRealms(REALMS);

/**
 * Journey "Chronicle" body — the realm list, rendered as 7 chapters
 * (Roman-numeral dividers + Cinzel title) with the realm groups clustered
 * under each chapter. Past chapters dim, current chapter is full opacity,
 * future chapters fade out. Only the realm the player is currently in
 * expands to show its sub-stages — everything else stays single-line so
 * the screen reads as a "lore arc" instead of a flat ladder.
 */
function JourneyBody({ realmIndex }) {
  const currentRef = useRef(null);

  // Scroll the current realm group into view on mount so returning players
  // land on their place in the chronicle, not at chapter I.
  useEffect(() => {
    if (currentRef.current) {
      currentRef.current.scrollIntoView({ block: 'center', behavior: 'instant' });
    }
  }, []);

  return (
    <div className="journey-chronicle">
      {CHAPTERS.map((chapter) => {
        const chapterGroups = GROUPS.filter(g => chapter.realmIndices.includes(g.realmNameIndex));
        if (chapterGroups.length === 0) return null;

        const lastIdxInChapter = Math.max(...chapterGroups.flatMap(g => g.entries.map(e => e.index)));
        const firstIdxInChapter = Math.min(...chapterGroups.flatMap(g => g.entries.map(e => e.index)));
        const chapterPast    = lastIdxInChapter  < realmIndex;
        const chapterCurrent = realmIndex >= firstIdxInChapter && realmIndex <= lastIdxInChapter;
        const chapterFuture  = firstIdxInChapter > realmIndex;
        const chapterCls =
          'jc-chapter' +
          (chapterPast    ? ' jc-chapter-past'    : '') +
          (chapterCurrent ? ' jc-chapter-current' : '') +
          (chapterFuture  ? ' jc-chapter-future'  : '');

        return (
          <section key={chapter.id} className={chapterCls}>
            <header className="jc-chapter-head">
              <span className="jc-chapter-num">{toRoman(chapter.id)}</span>
              <span className="jc-chapter-title">{chapter.title}</span>
              <span className="jc-chapter-rule" aria-hidden="true" />
            </header>

            {chapterGroups.map((group) => {
              const groupPast    = group.entries.every(e => e.index < realmIndex);
              const groupCurrent = group.entries.some(e => e.index === realmIndex);
              const groupFuture  = group.entries.every(e => e.index > realmIndex);
              const noSubStages  = group.entries.length === 1 && !group.entries[0].stage;
              const groupCls =
                'jc-realm' +
                (groupPast    ? ' jc-realm-past'    : '') +
                (groupCurrent ? ' jc-realm-current' : '') +
                (groupFuture  ? ' jc-realm-future'  : '');
              const completedCount = group.entries.filter(e => e.index < realmIndex).length;
              const totalCount = group.entries.length;
              const icon = REALM_ICONS[group.name];

              return (
                <div
                  key={group.name}
                  className={groupCls}
                  ref={groupCurrent ? currentRef : null}
                >
                  <div className="jc-realm-head">
                    <span className="jc-realm-icon">
                      {typeof icon === 'string' && icon.startsWith && icon.startsWith(BASE)
                        ? <img src={icon} alt="" className="jc-realm-icon-img" draggable="false" />
                        : <span className="jc-realm-icon-glyph">{REALM_GLYPHS[group.name] ?? icon ?? '•'}</span>}
                    </span>
                    <span className="jc-realm-name">{group.name}</span>
                    <span className="jc-realm-tag">
                      {groupPast
                        ? `${totalCount} ${totalCount === 1 ? 'stage' : 'stages'}`
                        : groupCurrent
                          ? `${completedCount + 1} / ${totalCount}`
                          : `${totalCount} ${totalCount === 1 ? 'stage' : 'stages'}`}
                    </span>
                    {groupPast && <span className="jc-realm-check" aria-hidden="true">✓</span>}
                  </div>

                  {/* Only the CURRENT realm expands to show sub-stages — past
                      and future stay collapsed so the chronicle reads as a
                      compact arc. Single-entry no-stage groups (Half-Step
                      Open Heaven) never expand. */}
                  {groupCurrent && !noSubStages && (
                    <div className="jc-stages">
                      {group.entries.map((entry, i) => {
                        const isCurrent = entry.index === realmIndex;
                        const isPast    = entry.index < realmIndex;
                        const hasSpark  = stageHasSpark(entry.index);
                        const cls = 'jc-stage' +
                          (i === 0 ? ' jc-stage-first' : '') +
                          (isCurrent ? ' jc-stage-current' : '') +
                          (isPast    ? ' jc-stage-past'    : '') +
                          (hasSpark  ? ' jc-stage-spark'   : '');

                        return (
                          <div key={entry.index} className={cls}>
                            <span className="jc-stage-dot">
                              {isPast    && <span className="jc-stage-check">✓</span>}
                              {isCurrent && <span className="jc-stage-pulse" />}
                            </span>
                            <span className="jc-stage-label">
                              {entry.stage}
                              <span className="jc-stage-num">#{entry.index + 1}</span>
                            </span>
                            <span className="jc-stage-cost-group">
                              {hasSpark ? (
                                <span
                                  className="jc-stage-spark-mark"
                                  title="Breaking through to this stage rewards a Qi Spark"
                                  aria-label="Qi Spark reward"
                                >✦</span>
                              ) : (
                                <span className="jc-stage-spark-mark jc-stage-spark-empty" aria-hidden="true" />
                              )}
                              <span className="jc-stage-cost">{fmtQi(entry.cost)} Qi</span>
                            </span>
                          </div>
                        );
                      })}
                    </div>
                  )}
                </div>
              );
            })}
          </section>
        );
      })}
    </div>
  );
}

export default JourneyBody;
