import { useEffect, useRef } from 'react';
import REALMS, { stageHasSpark } from '../data/realms';

// Pixel-art icons for each major realm, generated by scripts/gen_realm_icons.py.
// One file per realm, 64×64 RGBA in public/ui/realms/. Half-Step Open Heaven
// is a sub-stage placeholder with no dedicated icon — falls through to emoji.
const REALM_ICONS = {
  'Tempered Body':          '/ui/realms/tempered_body.png',
  'Qi Transformation':      '/ui/realms/qi_transformation.png',
  'True Element':           '/ui/realms/true_element.png',
  'Separation & Reunion':   '/ui/realms/separation_reunion.png',
  'Immortal Ascension':     '/ui/realms/immortal_ascension.png',
  'Saint':                  '/ui/realms/saint.png',
  'Saint King':             '/ui/realms/saint_king.png',
  'Origin Returning':       '/ui/realms/origin_returning.png',
  'Origin King':            '/ui/realms/origin_king.png',
  'Void King':              '/ui/realms/void_king.png',
  'Dao Source':             '/ui/realms/dao_source.png',
  'Emperor Realm':          '/ui/realms/emperor_realm.png',
  'Open Heaven':            '/ui/realms/open_heaven.png',
  'Half-Step Open Heaven':  '🌅',
};

function fmtQi(n) {
  if (n >= 1e12) return (n / 1e12).toFixed(1) + 'T';
  if (n >= 1e9)  return (n / 1e9).toFixed(1)  + 'B';
  if (n >= 1e6)  return (n / 1e6).toFixed(1)  + 'M';
  if (n >= 1e3)  return (n / 1e3).toFixed(1)  + 'K';
  return String(n);
}

// Group consecutive realm entries by name.
function groupRealms(realms) {
  const groups = [];
  let current = null;
  realms.forEach((r, idx) => {
    if (!current || current.name !== r.name) {
      current = { name: r.name, entries: [] };
      groups.push(current);
    }
    current.entries.push({ ...r, index: idx });
  });
  return groups;
}

const GROUPS = groupRealms(REALMS);

/**
 * Journey tab body for the Progress Hub modal. Extracted from the old
 * standalone JourneyModal so it can be rendered as one of three tabs
 * (Journey / Achievements / Stats) without duplicating the realm list
 * logic. The hub tab chip already reads "Journey", so the body skips a
 * redundant title and surfaces just the "N / M stages" meta inline with
 * the progress bar.
 */
function JourneyBody({ realmIndex }) {
  const currentRef = useRef(null);
  const listRef    = useRef(null);

  useEffect(() => {
    if (currentRef.current && listRef.current) {
      currentRef.current.scrollIntoView({ block: 'center', behavior: 'instant' });
    }
  }, []);

  return (
    <>
      <div className="journey-progress-meta">
        <span className="journey-progress-label">
          {realmIndex + 1} / {REALMS.length} stages
        </span>
      </div>

      <div className="journey-progress-bar">
        <div
          className="journey-progress-fill"
          style={{ width: `${((realmIndex + 1) / REALMS.length) * 100}%` }}
        />
      </div>

      <div className="journey-list" ref={listRef}>
        {GROUPS.map((group) => {
          const groupPast    = group.entries.every(e => e.index < realmIndex);
          const groupCurrent = group.entries.some(e => e.index === realmIndex);
          const groupFuture  = group.entries.every(e => e.index > realmIndex);
          // Single-entry groups with no sub-stage label (e.g. Half-Step Open Heaven)
          const noSubStages  = group.entries.length === 1 && !group.entries[0].stage;

          return (
            <div
              key={group.name}
              className={`journey-group${groupPast ? ' jg-past' : ''}${groupCurrent ? ' jg-current' : ''}${groupFuture ? ' jg-future' : ''}`}
            >
              <div className="journey-group-header">
                <span className="journey-group-icon">
                  {(() => {
                    const icon = REALM_ICONS[group.name];
                    if (!icon) return '•';
                    if (icon.startsWith('/')) {
                      return <img src={icon} alt="" className="journey-group-icon-img" />;
                    }
                    return icon;
                  })()}
                </span>
                <span className="journey-group-name">{group.name}</span>
                {groupPast    && <span className="journey-group-done">✓</span>}
                {groupCurrent && noSubStages && <span className="js-dot-pulse jg-header-pulse" />}
              </div>

              {!noSubStages && (
                <div className="journey-stages">
                  {group.entries.map((entry, i) => {
                    const isCurrent = entry.index === realmIndex;
                    const isPast    = entry.index < realmIndex;
                    // Does the breakthrough INTO this stage reward a Qi
                    // Spark? Computed deterministically from realms.js
                    // (Dial-12). The marker shows on the row whose BT
                    // grants the spark, i.e. the destination stage.
                    const hasSpark  = stageHasSpark(entry.index);
                    const cls = `journey-stage${i === 0 ? ' js-first' : ''}${isCurrent ? ' js-current' : ''}${isPast ? ' js-past' : ''}${hasSpark ? ' js-spark' : ''}`;

                    return (
                      <div
                        key={entry.index}
                        className={cls}
                        ref={isCurrent ? currentRef : null}
                      >
                        <div className="js-dot">
                          {isPast    && <span className="js-dot-check">✓</span>}
                          {isCurrent && <span className="js-dot-pulse" />}
                        </div>
                        <div className="js-body">
                          <span className="js-label">
                            {entry.stage}
                            {/* Global stage number across the whole journey
                                (#1 through #N). Dim secondary label so it
                                doesn't compete with the stage name. */}
                            <span className="js-stage-num">#{entry.index + 1}</span>
                          </span>
                          {/* Cost group: a fixed-width spark slot sits to
                              the LEFT of the qi value so every row's qi
                              number lines up in the same column whether
                              or not it rewards a spark. */}
                          <span className="js-cost-group">
                            {hasSpark ? (
                              <span
                                className="js-spark-mark"
                                title="Breaking through to this stage rewards a Qi Spark"
                                aria-label="Qi Spark reward"
                              >✦</span>
                            ) : (
                              <span className="js-spark-mark js-spark-empty" aria-hidden="true" />
                            )}
                            <span className="js-cost">{fmtQi(entry.cost)} Qi</span>
                          </span>
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </>
  );
}

export default JourneyBody;
